version: '3'
networks:
  lumen:
services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "8083:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - lumen

  mysql:
    image: mysql:8.0.26
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "9906:3306"
    environment:
      MYSQL_DATABASE: feedservice
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - lumen

  php:
    build:
      args:
        user: www-data
        uid: 1000
      context: .
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - ./src:/var/www/html
      - ./logs/php.log:/var/log/fpm.www.log
    ports:
      - "9000:9000"
    networks:
      - lumen
